### ISSUE TITLE
[FEATURE REQUEST] Tree to text

### ISSUE THREAD

**Issue by Crackroach** [aprilandjan/ascii-tree-generator#1]
First of all, I love your plugin, works great!

Second: I was wondering if you had any plans on adding a way to revert the "treefication" process? When you need to edit a tree that was made from text, we need to rewrite it entirely for editing it.

If I can help in any way, let me know!

**Comment by aprilandjan** [comment]
@Crackroach Thanks for your feedback and advise 😄

Currently there's no plan to add functions to turn formatted tree back to its origin text. I did considered that when creating this extension, but I feel that it would be troublesome to record (and the possible disposal) the origin text or handling transforming errors.

If you write a text, format it to tree strings, and you want to turn it back for editing quickly, you can just simply `undo` the formatting operation using the vscode editor `undo` ability. The default shortcut is <kbd>cmd</kbd>+<kbd>Z</kbd>.

Hope this helps!

**Comment by Crackroach** [comment]
@aprilandjan

The `ctrl + z` method won't do. It is ok when you haven't made any modification to the file and haven't exited it.

I wrote this regex `[└├]──|│ *| *(?=[└├│])` to overcome this problem.

All you have to do is press `ctrl + h` and copy-pate the regex in the top input. Don't forget to enable `regex search`. In the lower input type in the character you want for the text string. I personnally prefer the `#` for this.

**Comment by aprilandjan** [comment]
@Crackroach yes, there's definitely this kind of need.

I tried your regex and it is very neat! Maybe I can use this to add anther context-menu item in editor to implement this function, but it might be confusing if two much context-menu items exists. Do you have any suggestions?

**Comment by Crackroach** [comment]
@aprilandjan

I don't know how feasible is this idea:

Detect if you are highlighting a rendered tree then show the tree to text menu. Otherwise show the text to tree?

**Comment by aprilandjan** [comment]
@Crackroach Thanks for your suggestions!

I prefer the first plan, but not sure whether it is possible using vscode extension api. If not, the second is good, too. The third plan seems not friendly enough.

I'll take time to implement this in a few days. Thanks again 😄

**Comment by Wulfheart** [comment]
Is it already implemented? Definitely need it.

**Comment by aprilandjan** [comment]
@Wulfheart Yes, you can open the VS Code Command Palette and execute `Revert Tree Strings to Text` command to revert tree strings back to hash-style texts, in case that your undo history is lost for some reason 😃

**Comment by petr-ujezdsky** [comment]
@aprilandjan FYI it is not for users who has "lost undo history" or do not know how `Ctrl+Z` work.

You typically create the tree in some documentation and commit it. Later on you (or anyone else) want to edit it. Then this feature is crucial ;-)

**Comment by aprilandjan** [comment]
@petr-ujezdsky Yeah you are right, and we have this feature finally.

I do not use IntelliJ, maybe you can write one to archive same functionality 😃
