### ISSUE TITLE
Too slow even when generating tree for non `node_modules` folder

### ISSUE THREAD

**Issue by deadcoder0904** [aprilandjan/ascii-tree-generator#2]
I have a directory structure like 👇

```bash
del
└── globby
    └── glob
        └── minimatch
node_modules
```

But I think it scans `node_modules` as well because it's too slow. Like I've been waiting for 5 mins now & it hasn't showed output. It happened 2-3 times this week so I though this might be a bug :)

**Comment by deadcoder0904** [comment]
Ohh, fuck sorry. I was generating a tree structure for the last child directory all the time. That's why it didn't work. I guess you could send an error or print even if it's last directory. I couldn't figure this out for a week 😂

**Comment by aprilandjan** [comment]
@deadcoder0904 Thanks for your feedback!

I'll add some notification message for this case. Sorry to bother you about this problem! 😭

**Comment by deadcoder0904** [comment]
Haha no worries it was my mistake
