### ISSUE TITLE
Proposal: Configuration for char codes

### ISSUE THREAD

**Issue by rabanti-github** [aprilandjan/ascii-tree-generator#4]
Hi,

I introduced configurable character codes in a fork: https://github.com/rabanti-github/ascii-tree-generator. Additional features:

- Each character can be defined by its char code in the VSCode configuration
- Fallback to the default characters in case of an invalid char code
- Documentation with example configuration in the readme
- Test mode to disable user defined characters during unit tests (otherwise tests will fail)

Particular changes can be tracked in the commits: https://github.com/rabanti-github/ascii-tree-generator/commit/09d7ae933b673b5c7050691ca63a5baee18960f0 and https://github.com/rabanti-github/ascii-tree-generator/commit/118d3764ad1a581c35d0691d9998594ab4bcd339

What do you think about this approach?

Thank you in advance for your opinion.

**Comment by aprilandjan** [comment]
@rabanti-github Hi, thanks for your proposal! I checked your code, it's exactly what I wanted to add to this extension months ago. The functionality and implementation seems good. Would you please open a Pull Request into this repository?

**Comment by rabanti-github** [comment]
Thank you.
I will make a PR then.
However, there may be some rework on the configuration. Currently, changes on the settings only seems to have an effect after the restart of VS.

**Comment by aprilandjan** [comment]
@rabanti-github merged. Thanks very much!
