### ISSUE TITLE
don't use the navigation group of explore context

### ISSUE THREAD

**Issue by tjx666** [aprilandjan/ascii-tree-generator#7]
The navigation group should be used for those often-used operations, but I think generating tree is not an often-used operation.

It would be better to add the menu to bottom:
![screenshot_2020-02-21_13-20-34](https://user-images.githubusercontent.com/41773861/75006536-077e1400-54ad-11ea-8a43-18b5b8b4661f.png)

**Comment by aprilandjan** [comment]
@tjx666 you are right. Thanks for your advise!
